### ISSUE TITLE
The argument has lenght zero

### ISSUE THREAD

**Issue by devilmind81** [MateuszJalocha/Machine-Learning-football-result-prediction#1]
Hi Mateusz,
during execution of ML_MateuszJalocha.Rmd with RStudio, I'm obtaining an error at line 266:

```
...
if(results$HomeTeam == teams[i] & results$FTresults == "H") {
      sumcia <- match_points[length(match_points)] + 3
      match_points[j] <- sumcia
      homeOrAway_vec[j] <- "H"
    }
...
```

The error is:
`
Error in if (results$HomeTeam == teams[i] & results$FTresults == "H") { : 
  The argument has lenght zero
`
Let me know.
Thanks in advance.

**Comment by devilmind** [comment]
Hi, 
in order to fix the previouse error I had to replace all occurrences of FTresults with FTRes.
No I have an error at line 551:
``
Error in makeParamSet(makeDiscreteParam("k", values = seq(3, 6, 1)), makeDiscreteParam("distance",  : 
  I cannot find the function "makeParamSet"
``

can you help me here pls?

**Comment by devilmind** [comment]
In order to fix the previouse error I hade to replace all occurrences (7) of FTresults word with FTRes one in th eML_MateuszJalocha.Rmd .

Now I'm able to complete the execution, please update the file.

**Comment by MateuszJalocha** [comment]
Alright, thank you very much
